package com.talool.core;

/**
 * 
 * @author clintz
 * 
 */
public enum AcquireStatus
{
	PURCHASED, REDEEMED, REJECTED_CUSTOMER_SHARE, REJECTED_MERCHANT_SHARE, ACCEPTED_MERCHANT_SHARE, ACCEPTED_CUSTOMER_SHARE, PENDING_ACCEPT_MERCHANT_SHARE, PENDING_ACCEPT_CUSTOMER_SHARE;
}
