package com.talool.core;

import java.util.Date;
import java.util.Set;
import java.util.UUID;

import com.talool.domain.MerchantCodeImpl;

/**
 * An interface for groups of codes generated by merchants
 * 
 * 
 * @see MerchantCodeImpl
 * @author clintz
 * 
 */
public interface MerchantCodeGroup extends Identifiable
{
	public UUID getMerchantId();

	public Long getCreatedByMerchantAccountId();

	public UUID getPublisherId();

	public String getCodeGroupTitle();

	public String getCodeGroupNotes();

	public Short getTotalCodes();

	public Date getCreated();

	public Set<MerchantCode> getCodes();

}
