package com.talool.core;

import java.util.UUID;

import com.talool.domain.MerchantCodeGroupImpl;

/**
 * An interface for codes generated by merchants that can later be associated
 * with purchases. A good use case is school codes from merchants with a fund
 * raiser property = true .
 * 
 * @see MerchantCodeGroupImpl
 * 
 * @author clintz
 * 
 */
public interface MerchantCode extends Identifiable
{
	public MerchantCodeGroup getMerchantCodeGroupId();

	public String getCode();

	public UUID getDealOfferPurchaseId();
}
